package ui;

import javax.swing.ImageIcon;

/**
 *
 * @author JuanJoseMoya
 */
public class Chat extends javax.swing.JFrame {
    
    private hiloIO iO;
    /**
     * Creates new form Panel
     */
    public Chat(hiloIO iO) {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon smile = new ImageIcon("src/ui/images/sonrisa.png");
        ImageIcon sad = new ImageIcon("src/ui/images/sad.png");
        ImageIcon cool = new ImageIcon("src/ui/images/cool.png");
        this.iO=iO;
        JTextAreaMensaje.setLineWrap(true);
        jTextAreaPanel.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPanel = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListConectados = new javax.swing.JList();
        JTextAreaMensaje = new javax.swing.JTextArea();
        jButtonSmile = new javax.swing.JButton();
        jButtonCool = new javax.swing.JButton();
        jButtonSad = new javax.swing.JButton();
        jButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(655, 430));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaPanel.setEditable(false);
        jTextAreaPanel.setColumns(20);
        jTextAreaPanel.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPanel);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 285));

        jListConectados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListConectados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 111, 285));

        JTextAreaMensaje.setColumns(20);
        JTextAreaMensaje.setRows(5);
        jPanel1.add(JTextAreaMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 446, 47));

        jButtonSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/sonrisa.png"))); // NOI18N
        jButtonSmile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSmileActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSmile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 46, 35));

        jButtonCool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/cool.png"))); // NOI18N
        jButtonCool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoolActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCool, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 46, 35));

        jButtonSad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/sad.png"))); // NOI18N
        jButtonSad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 46, 35));

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 111, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoolActionPerformed
        String Mensaje;
        Mensaje=JTextAreaMensaje.getText()+" 8-1 ";
        JTextAreaMensaje.setText(Mensaje);
    }//GEN-LAST:event_jButtonCoolActionPerformed

    private void jButtonSadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSadActionPerformed
        String Mensaje;
        Mensaje=JTextAreaMensaje.getText()+" :-( ";
        JTextAreaMensaje.setText(Mensaje);
    }//GEN-LAST:event_jButtonSadActionPerformed

    private void jButtonSmileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSmileActionPerformed
        String Mensaje;
        Mensaje=JTextAreaMensaje.getText()+" :-) ";
        JTextAreaMensaje.setText(Mensaje);
        
    }//GEN-LAST:event_jButtonSmileActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        iO.enviarMensaje(JTextAreaMensaje.getText());
    }//GEN-LAST:event_jButtonEnviarActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTextAreaMensaje;
    private javax.swing.JButton jButtonCool;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonSad;
    private javax.swing.JButton jButtonSmile;
    private javax.swing.JList jListConectados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextAreaPanel
     */
    public javax.swing.JTextArea getjTextAreaPanel() {
        return jTextAreaPanel;
    }

    /**
     * @param jTextAreaPanel the jTextAreaPanel to set
     */
    public void setjTextAreaPanel(javax.swing.JTextArea jTextAreaPanel) {
        this.jTextAreaPanel = jTextAreaPanel;
    }

    /**
     * @return the jListConectados
     */
    public javax.swing.JList getjListConectados() {
        return jListConectados;
    }

    /**
     * @param jListConectados the jListConectados to set
     */
    public void setjListConectados(javax.swing.JList jListConectados) {
        this.jListConectados = jListConectados;
    }

   

   
}
