/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;

/**
 *
 * @author JuanJoseMoya
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Chat() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon smile = new ImageIcon("src/ui/images/sonrisa.png");
        ImageIcon sad = new ImageIcon("src/ui/images/sad.png");
        ImageIcon cool = new ImageIcon("src/ui/images/cool.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTextAreaMensaje = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaChat = new java.awt.TextArea();
        list1 = new java.awt.List();
        jPanelEmoticon = new javax.swing.JPanel();
        jButtonSad = new javax.swing.JButton();
        jButtonCool = new javax.swing.JButton();
        jButtonSmile = new javax.swing.JButton();
        jButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 524));

        JTextAreaMensaje.setColumns(20);
        JTextAreaMensaje.setRows(5);

        textAreaChat.setEditable(false);
        jScrollPane1.setViewportView(textAreaChat);

        jButtonSad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/sad.png"))); // NOI18N
        jButtonSad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSadActionPerformed(evt);
            }
        });

        jButtonCool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/cool.png"))); // NOI18N
        jButtonCool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoolActionPerformed(evt);
            }
        });

        jButtonSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/sonrisa.png"))); // NOI18N
        jButtonSmile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSmileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmoticonLayout = new javax.swing.GroupLayout(jPanelEmoticon);
        jPanelEmoticon.setLayout(jPanelEmoticonLayout);
        jPanelEmoticonLayout.setHorizontalGroup(
            jPanelEmoticonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmoticonLayout.createSequentialGroup()
                .addComponent(jButtonSmile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCool, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelEmoticonLayout.setVerticalGroup(
            jPanelEmoticonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jButtonSmile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonCool, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonSad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanelEmoticon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(JTextAreaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 189, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEmoticon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(JTextAreaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoolActionPerformed
        String Mensaje;
        Mensaje=JTextAreaMensaje.getText()+" 8-1 ";
        JTextAreaMensaje.setText(Mensaje);
    }//GEN-LAST:event_jButtonCoolActionPerformed

    private void jButtonSadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSadActionPerformed
        String Mensaje;
        Mensaje=JTextAreaMensaje.getText()+" :-( ";
        JTextAreaMensaje.setText(Mensaje);
    }//GEN-LAST:event_jButtonSadActionPerformed

    private void jButtonSmileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSmileActionPerformed
        String Mensaje;
        Mensaje=JTextAreaMensaje.getText()+" :-) ";
        JTextAreaMensaje.setText(Mensaje);
        
    }//GEN-LAST:event_jButtonSmileActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        String Mensaje;
        Mensaje=textAreaChat.getText();
        Mensaje=Mensaje+JTextAreaMensaje.getText()+"\n";
        textAreaChat.setText(Mensaje);
        JTextAreaMensaje.setText("");
        
        
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTextAreaMensaje;
    private javax.swing.JButton jButtonCool;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonSad;
    private javax.swing.JButton jButtonSmile;
    private javax.swing.JPanel jPanelEmoticon;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List list1;
    private java.awt.TextArea textAreaChat;
    // End of variables declaration//GEN-END:variables
}
